// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `colour`, `escape`

/// Smallest possible synchronous call, for timing a Dart to Rust round trip.
int ping({required int value}) =>
    RustLib.instance.api.crateApiCertPing(value: value);

/// Panics on a Rust worker thread. flutter_rust_bridge should turn this into
/// a Dart `PanicException` and the app should keep running.
Future<void> panicNow() => RustLib.instance.api.crateApiCertPanicNow();

/// Aborts the whole process, like a native crash in a plugin.
Future<void> abortNow() => RustLib.instance.api.crateApiCertAbortNow();

/// Allocates and touches `megabytes` more memory and keeps it, so repeated
/// calls walk the app towards AERA's memory limit. Returns the total held.
Future<BigInt> holdMemory({required int megabytes}) =>
    RustLib.instance.api.crateApiCertHoldMemory(megabytes: megabytes);

/// Frees everything [`hold_memory`] kept.
Future<void> releaseMemory() =>
    RustLib.instance.api.crateApiCertReleaseMemory();

/// Busy work split over `threads` Rust threads; returns elapsed microseconds.
Future<BigInt> spinThreads({
  required int threads,
  required BigInt iterations,
}) => RustLib.instance.api.crateApiCertSpinThreads(
  threads: threads,
  iterations: iterations,
);

/// Renders the Mandelbrot set as RGBA pixels, splitting rows across all CPUs.
/// `scale` is the width of the view in the complex plane.
Future<Uint8List> fractal({
  required int width,
  required int height,
  required double centerX,
  required double centerY,
  required double scale,
  required int maxIterations,
}) => RustLib.instance.api.crateApiCertFractal(
  width: width,
  height: height,
  centerX: centerX,
  centerY: centerY,
  scale: scale,
  maxIterations: maxIterations,
);
